plugins {
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'java-library'
    id 'io.freefair.lombok' version '8.6' apply false
    id 'com.avast.gradle.docker-compose' version '0.17.6' apply false
}

import groovy.json.JsonSlurper
import groovy.json.JsonOutput

apply from: "gradle/task/root/common.gradle"
apply from: "gradle/config/module.gradle"
apply from: "gradle/config/search.gradle"

// 1. Khai báo biến phiên bản Spring Cloud
ext {
    set('springCloudVersion', "2023.0.1")
}

def skipServiceList = []
def getSyncRegistry = { File file ->
    if (file.exists()) {
        try {
            return new JsonSlurper().parse(file)
        } catch (Exception e) {
            return [:]
        }
    }
    return [:]
}

subprojects {
    def RESET = "\u001B[0m"
    def BLUE = "\u001B[34m"
    def BOLD = "\u001B[1m"

    apply from: "${rootDir}/gradle/config/module.gradle"

    if (file("${projectDir}/gradle.properties").exists()) {

        File masterFile = file("master.json")
        File propertiesFile = file("properties.json")
        File registryFile = layout.buildDirectory.file("last-check.json").get().asFile

        HashMap registry = getSyncRegistry(registryFile) as HashMap

        if (masterFile.exists() && propertiesFile.exists()) {
            long currentMasterTime = masterFile.lastModified()
            long currentPropertiesTime = propertiesFile.lastModified()
            long lastMasterProcessed = registry.get("master", "0").toLong()
            long lastPropertiesProcessed = registry.get("properties", "0").toLong()

            ext.applyPluginAndDependencyToModule()
            ext.generateModuleDependList()
            ext.autoAddModuleDependencyDepend()

            // Chỉ chạy nếu file master.json mới hơn file marker
            if (currentMasterTime !=  lastMasterProcessed || currentPropertiesTime != lastPropertiesProcessed) {
                debugLog("${BLUE}${BOLD}==================================================")
                debugLog("🔍 BUILD MODULE ${project.hasProperty("SERVICE_NAME") ? project.SERVICE_NAME : project.name} AT ROOT BUILD.GRADLE")
                debugLog("${BLUE}==================================================${RESET}")

                if (currentMasterTime != lastMasterProcessed) {
                    // --- Logic của bạn ---
                    ext.buildModuleStructure()
                    ext.buildYMLFile()

                    ext.buildDefaultEnvStructure()
                    ext.buildProfileEnvStructure()

                    ext.buildReadmeStructure()
                }

                if (currentPropertiesTime != lastPropertiesProcessed) {

                }

                // 4. Cập nhật dữ liệu mới vào Registry
                registry["master"] = currentMasterTime.toString()
                registry["properties"] = currentPropertiesTime.toString()
                registry["last_sync_date"] = new Date().toString()

                // 5. Ghi Registry ra file JSON
                if (!registryFile.parentFile.exists()) registryFile.parentFile.mkdirs()
                registryFile.text = JsonOutput.prettyPrint(JsonOutput.toJson(registry))

                logger.lifecycle("💯 ${BLUE} FINISHED SETTING MODULE ${project.hasProperty("SERVICE_NAME") ? project.SERVICE_NAME : project.name} AT ROOT BUILD.GRADLE")
                logger.lifecycle("${BLUE}${BOLD}==================================================${RESET}\n\n\n")
            } else {
                debugLog("🔍 SKIP BUILD MODULE ${project.findProperty("SERVICE_NAME") ?: project.name}")
                skipServiceList << project.findProperty("SERVICE_NAME") ?: project.name
            }
        }

        apply plugin: 'io.spring.dependency-management'

        processResources{
            // 1. Chỉ định rõ ràng duy nhất file này được phép copy
            include 'application.yml'
            processResources{
                // 1. Chỉ định rõ ràng duy nhất file này được phép copy
                include 'application.yml'
                include '**'

                from ("${projectDir}/src/main/resources") {
                    // 2. (Tùy chọn) Nếu bạn muốn chắc chắn loại bỏ tất cả các file có đuôi .yml khác và .properties
                    exclude '**/application-*.yml'
                    exclude '**/*.properties'
                }
                include '**/api-descriptions.yml'
                include '**/api-params.yml'
                exclude 'application-merged.yml'
                // 3. Đặt chiến lược xử lý nếu trùng lặp (thường dùng trong Gradle mới)
                duplicatesStrategy = DuplicatesStrategy.INCLUDE
            }
            from ("${projectDir}/src/main/resources") {
                // 2. (Tùy chọn) Nếu bạn muốn chắc chắn loại bỏ tất cả các file có đuôi .yml khác và .properties
                exclude '**/application-*.yml'
                exclude '**/*.properties'
            }
            include '**/api-descriptions.yml'
            include '**/api-params.yml'
            exclude 'application-merged.yml'
            // 3. Đặt chiến lược xử lý nếu trùng lặp (thường dùng trong Gradle mới)
            duplicatesStrategy = DuplicatesStrategy.INCLUDE
        }

        bootJar {
            def projectPathAsFolder = project.path.replace(':', '/')
            destinationDirectory = rootProject.layout.buildDirectory.dir("jar/${projectPathAsFolder}")
        }
    }
}

afterEvaluate {
    ext.injectAndExtractAllModuleTask(skipServiceList)
    ext.generateProjectStructureFileTxt()

//    println tasks.collect { it.name }
}

allprojects {
    group = 'com.example.learning'
    version = '1.0.0'

    sourceCompatibility = '21'
    targetCompatibility = '21'

    dependencyManagement {
        imports {
            mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
        }
    }
    test {
        useJUnitPlatform()
    }

    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}




