plugins {
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'java-library'
    id 'io.freefair.lombok' version '8.6' apply false
    id 'com.avast.gradle.docker-compose' version '0.17.6' apply false
    id 'com.example.module-orchestration' apply false
    id 'com.example.root-orchestration'
}

// 1. Khai báo biến phiên bản Spring Cloud
ext {
    set('springCloudVersion', "2023.0.1")
}


subprojects {
    if (file("${projectDir}/gradle.properties").exists()) {
        apply plugin: 'com.example.module-orchestration'

        bootJar {
            def projectPathAsFolder = project.path.replace(':', '/')
            destinationDirectory = rootProject.layout.buildDirectory.dir("jar/${projectPathAsFolder}")
        }
    }
}

allprojects {
    group = 'com.example.learning'
    version = '1.0.0'

    pluginManager.withPlugin('java') {

        sourceCompatibility = '21'
        targetCompatibility = '21'

        test {
            useJUnitPlatform()
        }
    }

    pluginManager.withPlugin('io.spring.dependency-management') {

        dependencyManagement {
            imports {
                mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
            }
        }
    }



    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}




