# Nếu là file mẫu (file-based.yml) vui lòng không thêm cấu hình vào
# Nếu là các file application.yml tại module con , hãy thêm cấu hình phù hợp vào
---
# Cấu hình chung tại đây
management:
  tracing:
    sampling:
      probability: 1.0 # 1.0 là lấy 100% request (môi trường dev), production nên để 0.1
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

logging:
  pattern:
    # Thêm [%X{traceId:-}, %X{spanId:-}] vào pattern
    console: "%d{yyyy-MM-dd HH:mm:ss} %5p [%X{traceId:-}, %X{spanId:-}] --- [%thread] %-40.40logger{39} : %m%n"
---
# Cấu hình cho profile DEV
spring:
  config:
    activate:
      on-profile: dev



---
# Cấu hình cho profile LOC
spring:
  config:
    activate:
      on-profile: loc



---
# Cấu hình cho profile PRD
spring:
  config:
    activate:
      on-profile: prd