# Nếu là file mẫu (file-based.yml) vui lòng không thêm cấu hình vào
# Nếu là các file application.yml tại module con , hãy thêm cấu hình phù hợp vào
---
# Cấu hình chung tại đây
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

thread:
  thread-pool:
    core-size: 5
    max-size: 10
    queue-capacity: 100
    keep-alive: 60
    thread-name-prefix: "application-pool-"

---
# Cấu hình cho profile DEV
spring:
  config:
    activate:
      on-profile: dev



---
# Cấu hình cho profile LOC
spring:
  config:
    activate:
      on-profile: loc



---
# Cấu hình cho profile PRD
spring:
  config:
    activate:
      on-profile: prd