dependencies {
    implementation 'io.hawt:hawtio-springboot:4.0.0'
}

markdownTranslation {
    inputLanguage = 'vi'
    outputLanguage = 'en'
    fileLocation = 'menu/1.Basic/Test.md'
}

generateInternalReadmeMenu {
    location = 'readme/vi/menu/1.Basic/Basic.md'
}

generateFinalReadme {

    languages = [
            'vi',
            'en'
    ]
}

generateApiSwaggerDescription {
    languages = [
            'vi',
            'en'
    ]
}

